Repository codebooky/First-Contributions, pull requests merged in 2022-10, with the labels that each got.

#2 Added Step 1
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#3 Added Step 2
  README.md
Labels: hacktoberfest

#4 Added Step 3
  README.md
Labels: hacktoberfest

#7 Added image for 'Fork this Repo'
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#8 Make necessary changes and commit those changes
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#9 Push changes to GitHub
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#10 Submit your changes for review
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#11 Image resource not exist
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#13 Added translation
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 aniketjain-update-patch1
  py_pattern_programs/pattern1.py
Labels: hacktoberfest, hacktoberfest-accepted

#16 aniketjain-update-patch2
  src/pattern1.py
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create pattern.py
  Nikhil/pattern.py
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create pythonPattern.py
  Nikhil/pythonPattern.py
Labels: hacktoberfest, hacktoberfest-accepted

#20 Create pythonPattern.py
  Nikhil/pythonPattern.py
Labels: hacktoberfest, hacktoberfest-accepted

#23 Create main1.java
  main1.java
Labels: hacktoberfest, hacktoberfest-accepted

#25 Create Main3.java
  Prerit/Main3.java
Labels: hacktoberfest, hacktoberfest-accepted

#24 Create Main2.java
  Prerit/Main2.java
Labels: hacktoberfest, hacktoberfest-accepted

#26 Create Main4.java
  Prerit/Main4.java
Labels: hacktoberfest, hacktoberfest-accepted

#29 Duplicate file
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#30 Contributing
  Contributors.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#32 रिपॉज़िटरी को फॉर्क करना
  translations/README.hi.md
Labels: hacktoberfest, hacktoberfest-accepted

#34 Mini Projects
  Frontend Mini Projects/Technical Documentation/index.html
  Frontend Mini Projects/Technical Documentation/style.css
  Frontend Mini Projects/Tribute Page/index.html
  Frontend Mini Projects/Tribute Page/style.css
Labels: hacktoberfest, hacktoberfest-accepted
